services:
  db:
    image: postgres:latest
    container_name: walletdb
    environment:
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpassword
      POSTGRES_DB: walletdb
      POSTGRES_HOST: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
                -c shared_buffers=256MB
                -c effective_cache_size=768MB
                -c maintenance_work_mem=64MB
                -c checkpoint_completion_target=0.7
                -c wal_buffers=16MB
                -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U walletuser -d walletdb"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: 'True'

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - web
      - db
    command: locust -f locustfile.py --host http://web:8000

volumes:
  postgres_data: